kind: Deployment
apiVersion: apps/v1
metadata:
  name: ytf-typesense-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ytf-typesense
  template:
    metadata:
      labels:
        app: ytf-typesense
    spec:
      containers:
        - name: ytf-typesense
          image: typesense/typesense:0.25.1
          command:
            - "/bin/sh"
            - "-c"
            - "mkdir -p /data; /opt/typesense-server"
          ports:
            - name: typesense
              containerPort: 8108
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8108
          env:
            - name: TYPESENSE_DATA_DIR
              value: /data
            {{- range .Values.typesense.secret.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: ytf-typesense-secret
                  key: {{ .name }}
            {{- end }}
