kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.typesense.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {{ .Values.typesense.service.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .Values.typesense.service.labels | toYaml | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.github }}

      containers:
        - name: {{ .Values.typesense.deployment.name }}
          image: {{ .Values.typesense.deployment.image.name }}:{{ .Values.typesense.deployment.image.tag }}
          command:
            - "/bin/sh"
            - "-c"
            - "mkdir -p /data; /opt/typesense-server"
          ports:
            - {{ .Values.typesense.deployment.port | toYaml | nindent 14 }}
          env:
            - name: TYPESENSE_DATA_DIR
              value: /data
            {{- range .Values.typesense.deployment.secret.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.typesense.deployment.secret.name }}
                  key: {{ .name }}
            {{- end }}
