apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.typesense.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.class }}
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.Ingress.issuer }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: typesense-ingress
spec:
  tls:
    - hosts:
        - {{ .Values.common.baseDomain }}
      secretName: {{ .Values.common.certName }}
  rules:
    - host: {{ .Values.common.baseDomain }}
      http:
        paths:
          - path: /typesense(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.typesense.service.name }}
                port:
                  number: {{ .Values.typesense.service.port }}
