kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-typesense-service
  labels:
    app: ytf-typesense
spec:
  ports:
    - port: 8108
      targetPort: typesense
  selector:
    app: ytf-typesense
