nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com/:
    npmAuthToken: "${YTF_NPM_AUTH_TOKEN}"

npmScopes:
  yes-theory-fam:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
