version: "3.9"

services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
  server:
    image: yestheory-family-server:latest
    build:
      args:
        BACKEND_PORT: ${BACKEND_PORT:-5000}
      context: .
      dockerfile: packages/server/Dockerfile
    hostname: ${BACKEND_HOST:-server}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      PRISMA_DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_DB_NAME}?schema=public"
    depends_on:
      - postgres
  web:
    image: yestheory-family-web:latest
    build:
      args:
        - NEXT_PUBLIC_BACKEND_URL
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:3000"
