version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ytfe2e
      POSTGRES_PASSWORD: ytfe2e
      POSTGRES_DB: ytfe2e
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ytfe2e"]
      start_period: 2s
      interval: 1s

  server:
    image: ghcr.io/yes-theory-fam/yestheory-family-server:COMMIT_HASH
    hostname: server
    ports:
      - "5000:5000"
    environment:
      PRISMA_DATABASE_URL: "postgresql://ytfe2e:ytfe2e@postgres:5432/ytfe2e?schema=public"
      FRONTEND_HOST: "http://web:3000"

      IS_E2E: "true"

      DISCORD_BOT_TOKEN: skipped
      DISCORD_TARGET_GUILD: skipped

      DISCORD_ADMIN_ID: skipped
      YESBOT_API_TOKEN: yesbot-api-token

      DISCORD_CLIENT_ID: skipped
      DISCORD_CLIENT_SECRET: skipped
      DISCORD_SCOPES: skipped

      CMS_ENDPOINT: "http://cms:3001/api/graphql"
      CMS_API_KEY: e2e-api-key
    depends_on:
      cms:
        condition: 'service_healthy'
      postgres:
        condition: 'service_healthy'

  web:
    image: ghcr.io/yes-theory-fam/yestheory-family-web:COMMIT_HASH
    environment:
      SERVER_BACKEND_GRAPHQL_URL: http://server:5000/graphql
      FRONTEND_URL: http://web:3000
    ports:
      - "3000:3000"
    depends_on:
      - server

  cms:
    image: ghcr.io/yes-theory-fam/yestheory-family-cms:COMMIT_HASH
    environment:
      ENABLE_DATASEEDER: "true"
      PAYLOAD_SECRET: asdfghjkl
      DATABASE_URI: "postgresql://ytfe2e:ytfe2e@postgres:5432/payload?schema=public"
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_API_URL: http://typesense:8108
      BACKEND_URL: http://server:5000
      INTERNAL_BACKEND_URL: http://server:5001
      YESBOT_API_AUTH_TOKEN: yesbot-api-token
      INITIAL_ADMIN_ID: skipped
      PAYLOAD_API_KEY: e2e-api-key
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:3001/admin > /dev/null || exit 1"]
      start_period: 5s
      interval: 1s
      retries: 10
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: 'service_healthy'
      typesense:
        condition: 'service_started'

  typesense:
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
    volumes:
      - "typesense-data:/data"

  playwright:
    image: mcr.microsoft.com/playwright:v1.43.1-focal
    entrypoint: "/bin/bash"
    command: "./wait-for-it.sh -t 30 --strict server:5000 -- ./install-and-run.sh"
    working_dir: /e2e
    volumes:
      - ./packages/e2e:/e2e
    environment:
      FRONTEND_URL: http://web:3000
    depends_on:
      - web
      - server
      - cms
      - postgres
      - typesense

volumes:
  typesense-data:
