version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ytfe2e
      POSTGRES_PASSWORD: ytfe2e
      POSTGRES_DB: ytfe2e

  server:
    image: ghcr.io/yes-theory-fam/yestheory-family-server:COMMIT_HASH
    hostname: server
    ports:
      - "5000:5000"
    environment:
      PRISMA_DATABASE_URL: "postgresql://ytfe2e:ytfe2e@postgres:5432/ytfe2e?schema=public"
      FRONTEND_HOST: "http://web:3000"

      IS_E2E: "true"

      DISCORD_BOT_TOKEN: skipped
      DISCORD_TARGET_GUILD: skipped

      DISCORD_CLIENT_ID: skipped
      DISCORD_CLIENT_SECRET: skipped
      DISCORD_SCOPES: skipped

      CMS_ENDPOINT: "http://cms:3001/api/graphql"
    depends_on:
      - cms
      - postgres

  web:
    image: ghcr.io/yes-theory-fam/yestheory-family-web:COMMIT_HASH
    environment:
      SERVER_BACKEND_GRAPHQL_URL: http://server:5000/graphql
      FRONTEND_URL: http://web:3000
    ports:
      - "3000:3000"
    depends_on:
      - server

  cms:
    image: ghcr.io/yes-theory-fam/yestheory-family-cms:COMMIT_HASH
    environment:
      MONGODB_URI: mongodb://mongo/cms
      ENABLE_DATASEEDER: "true"
      PAYLOAD_SECRET: asdfghjkl
      INITIAL_ADMIN_MAIL: admin@example.com
      INITIAL_ADMIN_PASSWORD: example
      MONGO_USERNAME: ytfe2e
      MONGO_PASSWORD: ytfe2e
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_API_URL: http://typesense:8108
      SERVER_URL: http://localhost:3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - typesense

  mongo:
    image: mongo:6.0.5
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ytfe2e
      MONGO_INITDB_ROOT_PASSWORD: ytfe2e
    ports:
      - "27017:27017"

  typesense:
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
    volumes:
      - "typesense-data:/data"

  cypress:
    image: cypress/included:11.0.1
    entrypoint: "/bin/bash"
    command: "/wait-for-it.sh -t 30 --strict server:5000 -- ./cypress/install-and-run.sh"
    working_dir: /e2e
    volumes:
      - ./packages/web/cypress:/e2e/cypress
      - ./packages/web/cypress.config.ts:/e2e/cypress.config.ts
      - ./packages/web/cypress/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - web

volumes:
  typesense-data:
