version: "3.9"

services:
  postgres:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}

  typesense:
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_DATA_DIR: /data
    ports:
      - 8108:8108
    volumes:
      - "typesense-data:/data"

volumes:
  typesense-data:
