version: "3.9"

services:
  postgres:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}

  server:
    image: yestheory-family-server:latest
    build:
      args:
        BACKEND_PORT: ${BACKEND_PORT:-5000}
      context: .
      dockerfile: packages/server/Dockerfile
    profiles:
      - build
    hostname: ${BACKEND_HOST:-server}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      PRISMA_DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_DB_NAME}?schema=public"
    depends_on:
      - postgres
  web:
    image: yestheory-family-web:latest
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    profiles:
      - build
    ports:
      - "3000:3000"
    environment:
      SERVER_BACKEND_GRAPHQL_URL: http://server:5000/graphql
      FRONTEND_URL: http://web:3000

  typesense:
    image: typesense/typesense:0.24.0
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: 1234567890
      TYPESENSE_DATA_DIR: /data
    ports:
      - 8108:8108
    volumes:
      - "typesense-data:/data"

volumes:
  typesense-data:
