kind: Deployment
apiVersion: apps/v1
metadata:
  name: ytf-web-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ytf-web
  template:
    metadata:
      labels:
        app: ytf-web
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.github }}
      containers:
        - name: ytf-web
          image: {{ .Values.web.deployment.image.name }}:{{ .Values.web.deployment.image.tag }}
          ports:
            - name: next
              containerPort: 3000
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /
              port: 3000
          env:
            - name: SERVER_BACKEND_GRAPHQL_URL
              value: http://ytf-backend-service/graphql
            - name: TYPESENSE_DIRECT_URL
              value: http://ytf-typesense-service:8108
            - name: FRONTEND_URL
              value: https://{{ .Values.common.baseDomain }}
