apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytf-web-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication required - Work in Progress'
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
  labels:
    app: web-ingress
spec:
  tls:
    - hosts:
        - {{ .Values.common.baseDomain }}
      secretName: {{ .Values.common.certName }}
  rules:
    - host: {{ .Values.common.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytf-web-service
                port:
                  number: 80
