apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.web.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.class }}
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.Ingress.issuer }}
  labels:
    app: web-ingress
spec:
  tls:
    - hosts:
        - {{ .Values.web.ingress.host }}
      secretName: {{ .Values.web.ingress.certName }}
  rules:
    - host: {{ .Values.web.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.web.service.name }}
                port:
                  number: {{ .Values.web.service.port }}
