kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-web-service
  labels:
    app: ytf-web
spec:
  ports:
    - port: 80
      targetPort: next
  selector:
    app: ytf-web
