kind: Deployment
apiVersion: apps/v1
metadata:
  name: ytf-cms-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ytf-cms
  template:
    metadata:
      labels:
        app: ytf-cms
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.github }}
      containers:
        - name: ytf-cms
          image: {{ .Values.cms.deployment.image.name }}:{{ .Values.cms.deployment.image.tag }}
          ports:
            - name: payload
              containerPort: 3001
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /admin
              port: 3001
          volumeMounts:
            - mountPath: /app/packages/cms/dist/media
              name: cms-media-upload
          env:
            - name: ENABLE_DATASEEDER
              value: "true"
            - name: FRONTEND_URL
              value: https://{{ .Values.common.baseDomain }}
            - name: TYPESENSE_API_URL
              value: "http://ytf-typesense-service:8108"
            - name: BACKEND_URL
              value: http://ytf-backend-service
            - name: INTERNAL_BACKEND_URL
              value: http://ytf-backend-yesbot-service:5001
            {{- range .Values.cms.secret.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: ytf-cms-secret
                  key: {{ .name }}
            {{- end }}
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ytf-typesense-secret
                  key: TYPESENSE_API_KEY
      volumes:
        - name: cms-media-upload
          persistentVolumeClaim:
            claimName: cms-media-upload

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-media-upload
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
