kind: Deployment
apiVersion: apps/v1
metadata:
  name: ytf-cms-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ytf-cms
  template:
    metadata:
      labels:
        app: ytf-cms
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.github }}
      containers:
        - name: ytf-cms
          image: {{ .Values.cms.deployment.image.name }}:{{ .Values.cms.deployment.image.tag }}
          ports:
            - name: payload
              containerPort: 3001
          env:
            - name: ENABLE_DATASEEDER
              value: "true"
            - name: FRONTEND_URL
              value: https://{{ .Values.common.baseDomain }}
            - name: SERVER_URL
              value: "https://admin.{{ .Values.common.baseDomain }}"
            - name: TYPESENSE_API_URL
              value: "http://ytf-typesense-service:8108"
            {{- range .Values.cms.secret.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: ytf-cms-secret
                  key: {{ .name }}
            {{- end }}
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ytf-typesense-secret
                  key: TYPESENSE_API_KEY
