{{- with .Values.cms.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: ytf-cms-secret
data: {{- range $secret := .secrets }}
  {{ $secret.name }}: {{ $secret.value | toString | b64enc }}
  {{- end }}
{{- end }}
