kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-cms-service
  labels:
    app: ytf-cms
spec:
  ports:
    - port: 80
      targetPort: payload
  selector:
    app: ytf-cms
