/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    groupchats: Groupchat;
    'groupchat-keywords': GroupchatKeyword;
    feature: Feature;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  roles?: ('owner' | 'groupchats-admin' | 'groupchats')[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Groupchat {
  id: number;
  name: string;
  platform: 'discord' | 'facebook' | 'instagram' | 'signal' | 'telegram' | 'whatsapp';
  showUnauthenticated?: boolean | null;
  description?: string | null;
  url: string;
  keywords?: (number | GroupchatKeyword)[] | null;
  promoted?: number | null;
  owners?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface GroupchatKeyword {
  id: number;
  value?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Feature {
  id: number;
  name: string;
  pathPrefix: string;
  navPath?: string | null;
  teaserImage: number | Media;
  description: string;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}