name: Reusable Build
description: Action to build a TS project to a runnable Docker image

inputs:
  sub-project:
    description: 'The sub-project this build is running for. Used for tagging the image and resolve the Dockerfile'
    required: true

  token:
    description: 'GitHub Token to authenticate against the Package and Container registry'
    required: true

  build-args:
    description: 'Optional build args to be passed to the build'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-server-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-server-

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/yes-theory-fam/yestheory-family-${{ inputs.sub-project }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: ${{ inputs.build-args }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: ./
        file: ./packages/${{ inputs.sub-project }}/Dockerfile
        builder: ${{ steps.buildx.output.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
