{{- with .Values.backend.deployment.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
data: {{- range $secret := .secrets }}
  {{ $secret.name }}: {{ $secret.value | b64enc }}
  {{- end }}
{{- end }}
