kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-backend-service
  labels:
    app: ytf-backend
spec:
  ports:
    - port: 80
      targetPort: public
  selector:
    app: ytf-backend
