kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-backend-yesbot-service
  labels:
    app: ytf-backend
spec:
  ports:
    - port: 5001
      targetPort: yesbot
  selector:
    app: ytf-backend

---

kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-backend-yesbot-schema-service
  labels:
    app: ytf-backend
spec:
  ports:
    - port: 5002
      targetPort: yesbot-schema
  selector:
    app: ytf-backend
