kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.backend.yesbotService.name }}
  labels: {{ .Values.backend.service.labels | toYaml | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.backend.yesbotService.port }}
      targetPort: {{ .Values.backend.deployment.ports.yesbot.name }}
  selector: {{ .Values.backend.service.labels | toYaml | nindent 4 }}
