imagePullSecrets:
  github: github

# TODO Extract DB user/pwd/name to variables and reuse them if possible

ingress:
  class: public
  issuer: letsencrypt-prod
  basicAuth:
    enabled: false
    htpasswdEntry: foo:$apr1$example

common:
  baseDomain: yestheory.family
  certName: cert

cms:
  deployment:
    image:
      name: ghcr.io/yes-theory-fam/yestheory-family-cms
      tag: latest

  secret:
    secrets:
      - name: PAYLOAD_SECRET
        value:
      - name: INITIAL_ADMIN_ID
        value:
      - name: PAYLOAD_API_KEY
        value:
      - name: DATABASE_URI
        value: postgres://username:password@ytf-database-service:5432/payload
      - name: YESBOT_API_AUTH_TOKEN
        value:

web:
  deployment:
    image:
      name: ghcr.io/yes-theory-fam/yestheory-family-web
      tag: latest

backend:
  deployment:
    image:
      name: ghcr.io/yes-theory-fam/yestheory-family-server
      tag: latest

  secret:
    secrets:
      - name: PRISMA_DATABASE_URL
        value:
      - name: DISCORD_BOT_TOKEN
        value:
      - name: DISCORD_TARGET_GUILD
        value:
      - name: DISCORD_CLIENT_ID
        value:
      - name: DISCORD_CLIENT_SECRET
        value:
      - name: YESBOT_API_TOKEN
        value:
      - name: DISCORD_ADMIN_ID
        value:
      - name: CMS_API_KEY
        value:

typesense:
  secret:
    secrets:
      - name: TYPESENSE_API_KEY
        value:

database:
  create: false

  secret:
    secrets:
      - name: POSTGRES_PASSWORD
        value: yesbot
      - name: POSTGRES_USER
        value: yesbot
      - name: POSTGRES_DB
        value: yesbot
