name: 'Clean'
on: push

jobs:
  remove-test-containers:
    runs-on: ubuntu-latest
    steps:

      - name: Wait for e2e to complete
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-e2e-test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: e2e-test
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Delete server image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        continue-on-error: true
        if: ${{ github.event_name == 'pull_request' }}
        with:
          owner: yes-theory-fam
          name: yestheory-family-server
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ format('pr-{0}', github.event.pull_request.number) }}

      - name: Delete web image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        with:
          owner: yes-theory-fam
          name: yestheory-family-web
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ format('pr-{0}', github.event.pull_request.number) }}
