name: 'Lint and Test'
on: push

jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and lint"
        with:
          command: eslint:check

  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and check formatting"
        with:
          command: format:check

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and test"
        with:
          command: test
