name: 'Lint and Test'
on:
  push: null
  merge_group:
    types: [ checks_requested ]

jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and lint"
        with:
          command: eslint:check

  prettier:
    name: "Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and check formatting"
        with:
          command: prettier:check

  tsc-web:
    name: "TSC Web"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and tsc web"
        with:
          command: workspace @yestheory.family/web tsc --noEmit

  tsc-server:
    name: "TSC Server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and tsc server"
        with:
          command: workspace @yestheory.family/server tsc --noEmit

  tsc-cms:
    name: "TSC CMS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-action
        name: "Install and tsc cms"
        with:
          command: workspace @yestheory.family/cms tsc --noEmit
