{{- if .Values.database.create -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-database-deployment
spec:
  selector:
    matchLabels:
      app: ytf-database
  template:
    metadata:
      labels:
        app: ytf-database
    spec:
      containers:
        - name: ytf-database
          image: postgres:13
          ports:
            - name: postgres
              containerPort: 5432
          env:
            {{- range .Values.database.secret.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: ytf-database-secret
                  key: {{ .name }}
            {{- end }}
{{- end -}}
