{{- if .Values.database.create -}}
{{- with .Values.database.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: ytf-database-secret
data: {{- range $secret := .secrets }}
  {{ $secret.name }}: {{ $secret.value | toString | b64enc }}
  {{- end }}
{{- end }}
{{- end -}}
