{{- if .Values.database.create -}}
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: ytf-database-service
  labels:
    app: ytf-database
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: ytf-database
{{- end -}}
